config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  namespace :examples do
    get 'headings/good'
    get 'headings/bad'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/examples/headings_controller.rb
module Examples
  class HeadingsController < ApplicationController
    def good
      puts 'good'
    end

    def bad
      puts 'bad'
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/views/examples/headings/bad.html.erb
<div>
  <div class="h1">My favorite fruits</div>
  <p class="p">a list of fruits i like</p>
</div>
<div>
  <div class="h2">Citrus</div>
  <div>
    <div class="h3">Yuzu</div>
    <div class="p">Yuzu is, in my opinion, one of the most fragrent fruits.</div>
  </div>
  <div>
    <div class="h3">Pomelo</div>
    <p>Often, eaten during the winter, reminds me of home. They are really big</p>
  </div>
</div>
<div>
  <h2>Pitted</h2>
  <h3>Apricots</h3>
  <div>Apricots are great</div>
  <h3>Peaches</h3>
  <p>Peaches are great too</p>
</div>
<h2>Melons</h2>
melons are perhaps the most sweet.

app/views/examples/headings/good.html.erb
<h1>My favorite fruits</h1>
<p>a list of fruits i like</p>

<h2>Citrus</h2>
<h3>Yuzu</h3>
<p>Yuzu is, in my opinion, one of the most fragrent fruits.</p>
<h3>Pomelo</h3>
<p>Often, eaten during the winter, reminds me of home. They are really big</p>
<h2>Pitted</h2>
<h3>Apricots</h3>
<div>Apricots are great</div>
<h3>Peaches</h3>
<p>Peaches are great too</p>
<h2>Melons</h2>
melons are perhaps the most sweet.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConsiderateFrontend</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/home.html.erb
<h1>Welcome#home</h1>
<p>Find me in app/views/welcome/home.html.erb</p>
<%= link_to 'good', examples_headings_good_path%>